name: Build & Release

on:
  push:
    branches:
      - CICD

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
           java-version: '12.x'


      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - id: read-version
        uses: NiklasLehnfeld/flutter-version-number-action@main
        with:
          file-path: pubspec.yaml
      - run: echo "version ${{ steps.read-version.outputs.version-number }}"

      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --release

      - name: upload artefact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: wzieba/CICD
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: "GroupCicd"
          file: "build/app/outputs/flutter-apk/app-release.apk"
          notifyTesters: true
          debug: false

#      - name: upload Deploygate
#        uses: jmatsu/dg-upload-app-action@v0.2.2
#        with:
#          app_owner_name: KhanhTQ
#          api_token: ${{ secrets.DEPLOYGATE_API_TOKEN }}
#          app_file_path: "build/app/outputs/flutter-apk/app-release.apk"
#          package_name: "CICD"
#          message: "cicd"

